### PR TITLE
Fix separator style on Fumi

### PR DESCRIPTION
**Pull request by ThePaulMcBride**
Fixed issues where the separator was positioned at the top of the input instead of centered

### CODE REVIEW

**Comment by halilb** [comment]
Thanks for your contribution @ThePaulMcBride!

**Comment by Tom29** [comment]
Still got separator at the top of input.

**Comment by Tom29** [comment]
Have you guys fixed it? I install from main repo, still have wrong position of separator.

**Comment by ThePaulMcBride** [comment]
This is fixed, it just looks like it hasn't been released on NPM yet. Maybe @halilb can look at this?

Until then, you could install it directly from github. Check the npm docs on how to do this.

**Comment by halilb** [comment]
@ThePaulMcBride is right. That wasn't available on npm and I just published 0.4.0 release that contains this fix. You can use that version @Tom29.

**Pull request merged**
